version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
     - image: google/dart:2.0.0
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: >
            apt-get update &&
            apt-get install -y xvfb &&
            apt-get install -y zip unzip wget &&
            curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&
            sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' &&
            apt-get update &&
            apt-get install -y google-chrome-stable build-essential jq git openssh-server &&
            apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      - run:
          command: >
            Xvfb :99 -screen 0 1280x1024x24
            export DISPLAY=:99
          background: true
      - run:
          command: >
            wget https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip &&
            unzip chromedriver_linux64.zip &&
            mv chromedriver /usr/bin/chromedriver &&
            chmod +x /usr/bin/chromedriver &&
            rm chromedriver_linux64.zip &&
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash &&
            export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" &&
            nvm install --lts=carbon &&
            cd $HOME/project &&
            npm i parcel-bundler -D &&
            npm test
            