version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
     - image: google/dart:2.0.0
    steps:
      - checkout # check out the code in the project directory
      - run: "sudo chmod +x .circleci/run.sh&&bash .circleci/run.sh" # run the all tests