version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8.9.0 # the primary container, where your job's commands are run
      - image: google/dart:2.0.0
    steps:
      - checkout # check out the code in the project directory
      - run: "sudo npm install parcel-bundler -g && sudo npm run test" # run the all tests