name: helloworld
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: neutrino2211 <email@example.com>

environment:
  sdk: '>=1.13.0 <3.0.0'

dependencies:
  js: '^0.6.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
